jwt_secret = "scholarship arrangement system"
max_ping_count = 3
file_storage = "./statics"
token_expired = 7200
port = ":4096"
url = "http://127.0.0.1:4096"

[mysql]
dbname = "reward"
addr = "localhost:3306"
username = "mochigo"
password = "1234"
